### ISSUE TITLE
Support for aarch64-apple-darwin target?

### ISSUE THREAD

**Issue by repi** [sonos/tract#406] opened 2020-11-15 13:03 UTC
Hi, thanks for this wonderful project, we've been happily using tract for inference here at [Embark](https://embark.games)!

Now with the new Macs with Apple Silicon (ARM CPU) coming out next week, has there been any work or plans to support the Rust `aarch64-apple-darwin` target for tract to natively support the new CPUs?

Building latest `main` branch with `cargo +nightly build --target aarch64-apple-darwin` currently results in the following linking error:

```
  = note: Undefined symbols for architecture arm64:
            "_arm64simd_tanh_f32_4n", referenced from:
                _$LT$tract_linalg..arm64..arm64simd..TanhF32x4n$u20$as$u20$tract_linalg..frame..tanh..TanhKer$LT$f32$GT$$GT$::run::hc5523bbca3708e05 in libtract_linalg-57c6fa57aa08120b.rlib(tract_linalg-57c6fa57aa08120b.3crkiibtqh2cndxp.rcgu.o)
            "_arm64simd_sigmoid_f32_4n", referenced from:
                _$LT$tract_linalg..arm64..arm64simd..SigmoidF32x4n$u20$as$u20$tract_linalg..frame..sigmoid..SigmoidKer$LT$f32$GT$$GT$::run::hef8fe752d6eeca31 in libtract_linalg-57c6fa57aa08120b.rlib(tract_linalg-57c6fa57aa08120b.3crkiibtqh2cndxp.rcgu.o)
            "_arm64simd_mmm_i8_8x8", referenced from:
                _$LT$tract_linalg..arm64..arm64simd..MatMatMulI8x8x8$u20$as$u20$tract_linalg..frame..mmm..kernel..MatMatMulKer$LT$i32$GT$$GT$::kernel::hff6b1704fcb0075d in libtract_linalg-57c6fa57aa08120b.rlib(tract_linalg-57c6fa57aa08120b.3crkiibtqh2cndxp.rcgu.o)
                _$LT$tract_linalg..arm64..arm64simd..MatMatMulI8xI32x8x8$u20$as$u20$tract_linalg..frame..mmm..kernel..MatMatMulKer$LT$i32$GT$$GT$::kernel::hea7df096a81286ed in libtract_linalg-57c6fa57aa08120b.rlib(tract_linalg-57c6fa57aa08120b.3crkiibtqh2cndxp.rcgu.o)
            "_arm64simd_mmm_f32_8x8_gen", referenced from:
                _$LT$tract_linalg..arm64..arm64simd..MatMatMulF32x8x8$u20$as$u20$tract_linalg..frame..mmm..kernel..MatMatMulKer$LT$f32$GT$$GT$::kernel::hb710f392508e1065 in libtract_linalg-57c6fa57aa08120b.rlib(tract_linalg-57c6fa57aa08120b.3crkiibtqh2cndxp.rcgu.o)
            "_arm64simd_mmm_f32_8x8_a5x", referenced from:
                _$LT$tract_linalg..arm64..arm64simd..MatMatMulF32x8x8A5x$u20$as$u20$tract_linalg..frame..mmm..kernel..MatMatMulKer$LT$f32$GT$$GT$::kernel::h6bb73b2f6e3a704c in libtract_linalg-57c6fa57aa08120b.rlib(tract_linalg-57c6fa57aa08120b.3crkiibtqh2cndxp.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kali** [comment] 2020-11-15 14:31
Hey ! Thanks for the kind words !

Support is definitely on the map: my M1 13" is on the way.

If you want to beat me to it, I assume the matter is only about fixing a few conditional compilation flags... I can not say for sure, but having a look in linalg:
* build.rs must build the right kernels (arm64simd). I think it does in the current state.
* arm64/arm64simd/ are the neon implementation we want build.rs to build. But darwin assumes free standing functions symbols are prefixed by an "_", so this need fixing. I think this is the cause of your issue. You could use https://github.com/sonos/tract/blob/main/linalg/x86_64/fma/fma_mmm_f32_16x6.tmpl#L23 as a model for inspiration, just choose the right function name (and maybe a flag or two) depending on the target.
* runtime checks in src/arm64.rs are likely to crash, as they assume /proc/cpuinfo. This will need to be put behind a conditional compilation section checking for linux. When we are targetting aarch64/darwin, we can safely pick the non-A5X configuration. I suspect it might just be better for M1 and we'll try to do better later.

Have fun ! Brand new architectures are always a bit of an adventure...

**Comment by kali** [comment] 2020-11-25 12:57
Here we go. See #411 . Everything is not fully baked yet on rustup, but I got it to work. I also needed to install protobof from homebrew as prost does not yet know what protoc to download to pre-process the protobuf files. But tract works, and on the one model I tried, performance is 23% better than on a i9 9900K workstation !

**Comment by repi** [comment] 2020-11-25 12:58
@kali that's awesome! and mighty impressive performance :)

**Comment by hrydgard** [comment] 2020-12-11 08:47
Sounds great! Just noting that prost is now fixed (or rather, worked-around).

**Comment by kali** [comment] 2020-12-11 08:52
ok, i will cut a release with the fixes on my side later today

**Comment by kali** [comment] 2020-12-11 19:00
I will consider this issue closed, even if we need the fix in prost to get released. In the meantime, installing protobuf with homebrew works.

**Closed by kali** 2020-12-11 19:00 UTC
